name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

permissions:
  contents: read
  pages: write
  id-token: write

# Temporarily disable concurrency to ensure clean deployments
# concurrency:
#   group: "pages"
#   cancel-in-progress: false

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Clear build cache
        run: rm -rf .svelte-kit build node_modules/.cache

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test:unit

      - name: Build
        env:
          BASE_PATH: '/propfit-app'
        run: pnpm build

      - name: List build output
        run: |
          echo "Build directory contents:"
          ls -la build/
          echo "Assets directory:"
          ls -la build/_app/immutable/assets/ || echo "Assets directory not found"
          echo "Entry directory:"
          ls -la build/_app/immutable/entry/ || echo "Entry directory not found"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
